#!/bin/bash

echo "🔧 Installing nodemon..."
npm install

echo ""
echo "✅ Fixes applied successfully!"
echo ""
echo "📋 Changes made:"
echo "  1. ✅ Created centralized config (src/config/env.js)"
echo "  2. ✅ Fixed multiple dotenv injections"
echo "  3. ✅ Added nodemon for better watch mode"
echo "  4. ✅ Updated scripts (npm run dev, npm start)"
echo "  5. ✅ Added NODE_ENV=production to start script"
echo ""
echo "🚀 Next steps:"
echo ""
echo "  Development:"
echo "    npm run dev          # Backend with nodemon"
echo "    cd frontend && npm run dev  # Frontend"
echo ""
echo "  Production:"
echo "    npm start            # Backend (NODE_ENV=production)"
echo "    cd frontend && npm run build && npm start  # Frontend"
echo ""
echo "  Optional - Get WalletConnect Project ID:"
echo "    1. Visit: https://cloud.walletconnect.com/"
echo "    2. Create free account"
echo "    3. Create new project"
echo "    4. Copy Project ID"
echo "    5. Add to frontend/.env:"
echo "       NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=your_project_id"
echo ""
echo "✨ Ready to go!"
