/**
 * EmailService - Send briefings and alerts via email
 */
import nodemailerPkg from 'nodemailer';
const nodemailer = nodemailerPkg.default || nodemailerPkg;

export class EmailService {
  constructor() {
    this.transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: process.env.SMTP_PORT || 587,
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    });
  }

  async sendBriefing(to, briefing) {
    try {
      const subject = `MetaGauge ${briefing.type.charAt(0).toUpperCase() + briefing.type.slice(1)} Brief`;
      
      const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #2563eb;">${briefing.title}</h2>
          <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            ${briefing.content.replace(/\n/g, '<br>')}
          </div>
          <p style="color: #64748b; font-size: 14px;">
            Generated by MetaGauge AI on ${new Date(briefing.createdAt).toLocaleDateString()}
          </p>
        </div>
      `;

      await this.transporter.sendMail({
        from: process.env.FROM_EMAIL || 'noreply@metagauge.io',
        to,
        subject,
        html,
        attachments: briefing.attachment ? [{ filename: briefing.attachment.filename, content: briefing.attachment.content }] : [],
      });

      console.log(`Briefing sent to ${to}`);
      return true;
    } catch (error) {
      console.error('Email send failed:', error);
      return false;
    }
  }

  async sendAlert(to, alert) {
    try {
      const subject = `MetaGauge Alert: ${alert.title}`;
      
      const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: ${alert.severity === 'high' ? '#fef2f2' : '#fefce8'}; padding: 20px; border-radius: 8px; border-left: 4px solid ${alert.severity === 'high' ? '#ef4444' : '#f59e0b'};">
            <h2 style="color: ${alert.severity === 'high' ? '#dc2626' : '#d97706'}; margin-top: 0;">
              ${alert.title}
            </h2>
            <p style="margin: 10px 0;">${alert.message}</p>
            <p style="color: #64748b; font-size: 14px; margin-bottom: 0;">
              Contract: ${alert.contractId} | ${new Date(alert.createdAt).toLocaleString()}
            </p>
          </div>
        </div>
      `;

      await this.transporter.sendMail({
        from: process.env.FROM_EMAIL || 'noreply@metagauge.io',
        to,
        subject,
        html
      });

      console.log(`Alert sent to ${to}`);
      return true;
    } catch (error) {
      console.error('Alert email send failed:', error);
      return false;
    }
  }
}
