/**
 * FinancialPDFGenerator
 * Generates investor-grade PDF financial reports using pdfkit.
 * Standard data room format: clean, minimal, professional.
 */
import PDFDocument from 'pdfkit';
import { createWriteStream, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '../../reports/financial');

// ── Brand colours ──────────────────────────────────────────────────────────
const C = {
  black:    '#0a0a0a',
  white:    '#ffffff',
  accent:   '#1a1a2e',    // dark navy — professional data room feel
  mid:      '#4a5568',    // body text
  light:    '#e2e8f0',    // table borders / dividers
  pos:      '#22543d',    // positive numbers (green)
  neg:      '#742a2a',    // negative numbers (red)
  posLight: '#f0fff4',
  negLight: '#fff5f5',
  pageW:    595,          // A4 width in points
  pageH:    842,          // A4 height in points
  marginX:  56,
  marginY:  56,
};

const bodyW = C.pageW - C.marginX * 2;

// ── Helpers ────────────────────────────────────────────────────────────────

function usd(n) {
  if (n == null || isNaN(n)) return '$0.00';
  const abs = Math.abs(n);
  const str = abs.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  return n < 0 ? `($${str})` : `$${str}`;
}

function pct(n) {
  if (n == null || isNaN(n)) return '0%';
  return `${Number(n).toFixed(1)}%`;
}

function ensureDir(filePath) {
  mkdirSync(dirname(filePath), { recursive: true });
}

// ── PDF builder class ──────────────────────────────────────────────────────

class PDFBuilder {
  constructor(doc) {
    this.doc = doc;
    this.y = C.marginY;
  }

  // Move to next line
  nl(h = 14) { this.y += h; }

  // Draw a horizontal rule
  hr(color = C.light, thickness = 0.5) {
    this.doc.moveTo(C.marginX, this.y)
      .lineTo(C.pageW - C.marginX, this.y)
      .strokeColor(color).lineWidth(thickness).stroke();
    this.nl(8);
  }

  // Section heading
  heading(text, opts = {}) {
    const size = opts.size || 11;
    this.doc.fontSize(size).font('Helvetica-Bold')
      .fillColor(opts.color || C.accent)
      .text(text, C.marginX, this.y, { width: bodyW });
    this.y = this.doc.y + 4;
  }

  // Body text
  body(text, opts = {}) {
    this.doc.fontSize(opts.size || 8.5).font(opts.bold ? 'Helvetica-Bold' : 'Helvetica')
      .fillColor(opts.color || C.mid)
      .text(text, opts.x || C.marginX, this.y, { width: opts.width || bodyW, lineGap: 3 });
    this.y = this.doc.y + (opts.gap || 4);
  }

  // Italic caption
  caption(text) {
    this.doc.fontSize(7.5).font('Helvetica-Oblique').fillColor('#718096')
      .text(text, C.marginX, this.y, { width: bodyW });
    this.y = this.doc.y + 4;
  }

  // Table row — cols: [{ text, width, align, bold, color }]
  tableRow(cols, opts = {}) {
    const rowH = opts.rowH || 18;
    const bgColor = opts.bg;
    if (bgColor) {
      this.doc.rect(C.marginX, this.y, bodyW, rowH).fillColor(bgColor).fill();
    }
    let x = C.marginX;
    for (const col of cols) {
      const align = col.align || 'left';
      const color = col.color || C.black;
      this.doc.fontSize(8).font(col.bold ? 'Helvetica-Bold' : 'Helvetica')
        .fillColor(color)
        .text(col.text || '', x + 4, this.y + 4, { width: (col.width || 100) - 8, align });
      x += col.width || 100;
    }
    this.y += rowH;
  }

  // Table header row
  tableHeader(cols) {
    this.tableRow(cols.map(c => ({ ...c, bold: true, color: C.white })), { bg: C.accent, rowH: 20 });
  }

  // Number row with sign-colour
  financialRow(label, value, indent = 0, subtotal = false) {
    const isNeg = typeof value === 'number' && value < 0;
    const display = typeof value === 'number' ? usd(value) : (value || '—');
    const color = typeof value === 'number' ? (value < 0 ? C.neg : C.black) : C.mid;
    this.tableRow([
      { text: ' '.repeat(indent * 2) + label, width: bodyW * 0.7, bold: subtotal },
      { text: display, width: bodyW * 0.3, align: 'right', bold: subtotal, color },
    ], subtotal ? { bg: '#f7fafc' } : {});
  }

  // Page footer
  footer(pageNum, totalPages) {
    const y = C.pageH - 36;
    this.doc.fontSize(7).font('Helvetica').fillColor('#a0aec0')
      .text('Confidential — Generated by MetaGauge | metagauge.io', C.marginX, y, { width: bodyW * 0.7 })
      .text(`Page ${pageNum} of ${totalPages}`, C.pageW - C.marginX - 80, y, { width: 80, align: 'right' });
  }

  // Force new page
  newPage() {
    this.doc.addPage();
    this.y = C.marginY;
  }

  // Check if we need a new page (leave bottom margin)
  checkPage(needed = 60) {
    if (this.y + needed > C.pageH - 80) this.newPage();
  }
}

// ── Page renderers ─────────────────────────────────────────────────────────

function renderCover(b, docs, projectName, period, chain) {
  // Full-page dark background
  b.doc.rect(0, 0, C.pageW, C.pageH).fillColor(C.accent).fill();

  // MetaGauge wordmark
  b.doc.fontSize(13).font('Helvetica-Bold').fillColor(C.white)
    .text('MetaGauge', C.marginX, 90);
  b.doc.fontSize(8).font('Helvetica').fillColor('#a0aec0')
    .text('Financial Intelligence Platform', C.marginX, 108);

  // Divider
  b.doc.moveTo(C.marginX, 130).lineTo(C.pageW - C.marginX, 130)
    .strokeColor('#2d3748').lineWidth(1).stroke();

  // Title
  b.doc.fontSize(26).font('Helvetica-Bold').fillColor(C.white)
    .text('Financial Intelligence Report', C.marginX, 180, { width: bodyW });

  b.doc.fontSize(14).font('Helvetica').fillColor('#a0aec0')
    .text(projectName, C.marginX, 225)
    .text(period + ' · ' + (chain || 'Ethereum'), C.marginX, 245);

  // Confidential badge
  b.doc.rect(C.marginX, 300, 100, 24).fillColor('#c53030').fill();
  b.doc.fontSize(9).font('Helvetica-Bold').fillColor(C.white)
    .text('CONFIDENTIAL', C.marginX + 10, 307);

  // Generated date
  b.doc.fontSize(8).font('Helvetica').fillColor('#718096')
    .text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, C.marginX, C.pageH - 70);
}

function renderExecutiveSummary(b, docs) {
  b.newPage();
  b.heading('Executive Summary', { size: 14 });
  b.hr();

  if (docs.executive_summary) {
    b.body(docs.executive_summary, { size: 9, gap: 8 });
  }

  b.nl(8);

  // Key highlights box
  b.heading('Key Highlights', { size: 10 });
  b.nl(4);

  const pl = docs.income_statement;
  const cf = docs.cash_flow_statement;
  const ue = docs.unit_economics;
  const kpi = docs.kpi_dashboard;

  const highlights = [
    ['Total Revenue', usd(pl?.revenue?.total_revenue)],
    ['Gross Margin', pct(pl?.gross_margin_pct)],
    ['Net Profit/Loss', usd(pl?.net_profit)],
    ['Monthly Burn', usd(cf?.summary?.monthly_burn_rate)],
    ['Cash Runway', cf?.summary?.runway_months ? `${Math.floor(cf.summary.runway_months)} months` : 'N/A'],
    ['Total Users', (kpi?.kpis?.users?.total || 0).toLocaleString()],
    ['LTV:CAC', ue?.ratios?.ltv_cac_label || 'N/A'],
    ['Retention', pct(kpi?.kpis?.engagement?.retention_rate)],
  ];

  b.tableHeader([
    { text: 'Metric', width: bodyW * 0.5 },
    { text: 'Value', width: bodyW * 0.5 },
  ]);
  let alt = false;
  for (const [metric, value] of highlights) {
    b.tableRow([
      { text: metric, width: bodyW * 0.5 },
      { text: value, width: bodyW * 0.5, bold: true },
    ], alt ? { bg: '#f7fafc' } : {});
    alt = !alt;
  }
}

function renderIncomeStatement(b, docs) {
  b.newPage();
  b.heading('Income Statement (P&L)', { size: 14 });
  b.caption(`Period: ${docs.period} | Currency: USD`);
  b.hr();

  const pl = docs.income_statement;
  if (!pl) { b.body('No data available.'); return; }

  b.heading('Revenue', { size: 9 });
  b.financialRow('Protocol Revenue', pl.revenue?.protocol_revenue, 1);
  b.financialRow('Token Revenue', pl.revenue?.token_revenue, 1);
  b.financialRow('Off-chain Revenue', pl.revenue?.off_chain_revenue, 1);
  b.financialRow('Total Revenue', pl.revenue?.total_revenue, 0, true);

  b.nl(6);
  b.heading('Cost of Revenue (COGS)', { size: 9 });
  b.financialRow('Gas Subsidies', pl.cost_of_revenue?.gas_subsidies, 1);
  b.financialRow('Infrastructure', pl.cost_of_revenue?.infrastructure, 1);
  b.financialRow('Total COGS', pl.cost_of_revenue?.total_cogs, 0, true);
  b.financialRow('Gross Profit', pl.gross_profit, 0, true);
  b.financialRow('Gross Margin %', pct(pl.gross_margin_pct), 0);

  b.nl(6);
  b.heading('Operating Expenses', { size: 9 });
  b.financialRow('Marketing & Advertising', pl.operating_expenses?.marketing, 1);
  b.financialRow('Payroll', pl.operating_expenses?.payroll, 1);
  b.financialRow('Legal & Audit', pl.operating_expenses?.legal_audit, 1);
  b.financialRow('Other Operating', pl.operating_expenses?.other, 1);
  b.financialRow('Total OpEx', pl.operating_expenses?.total_opex, 0, true);

  b.nl(6);
  b.financialRow('EBITDA', pl.ebitda, 0, true);
  b.financialRow('Net Profit / Loss', pl.net_profit, 0, true);
  b.financialRow('Net Margin %', pct(pl.net_margin_pct), 0);

  b.nl(8);
  b.heading('Per-Transaction Economics', { size: 9 });
  b.financialRow('Revenue per Transaction', pl.per_transaction?.revenue_per_tx, 1);
  b.financialRow('Cost per Transaction', pl.per_transaction?.cost_per_tx, 1);
  b.financialRow('Profit per Transaction', pl.per_transaction?.profit_per_tx, 1);
  b.financialRow('Total Transactions', pl.per_transaction?.total_transactions?.toLocaleString(), 1);

  if (docs.cfo_commentary?.pl) {
    b.nl(10);
    b.heading('CFO Commentary', { size: 9 });
    b.hr('#e2e8f0', 0.5);
    b.body(docs.cfo_commentary.pl, { size: 8.5, gap: 6 });
  }
}

function renderCashFlow(b, docs) {
  b.newPage();
  b.heading('Cash Flow Statement', { size: 14 });
  b.caption(`Period: ${docs.period} | Currency: USD`);
  b.hr();

  const cf = docs.cash_flow_statement;
  if (!cf) { b.body('No data available.'); return; }

  b.heading('Operating Activities', { size: 9 });
  b.financialRow('Cash from Protocol Fees', cf.operating?.cash_from_protocol, 1);
  b.financialRow('Cash from Off-chain Revenue', cf.operating?.cash_from_off_chain, 1);
  b.financialRow('Total Cash Inflows', cf.operating?.total_cash_inflows, 0, true);
  b.nl(4);
  b.financialRow('Cash Paid — Payroll', -(cf.operating?.cash_paid_payroll || 0), 1);
  b.financialRow('Cash Paid — Marketing', -(cf.operating?.cash_paid_marketing || 0), 1);
  b.financialRow('Cash Paid — Infrastructure', -(cf.operating?.cash_paid_infra || 0), 1);
  b.financialRow('Cash Paid — Legal/Audit', -(cf.operating?.cash_paid_legal || 0), 1);
  b.financialRow('Cash Paid — Gas Subsidy', -(cf.operating?.cash_paid_gas_subsidy || 0), 1);
  b.financialRow('Total Cash Outflows', -(cf.operating?.total_cash_outflows || 0), 0, true);
  b.financialRow('Net Operating Cash Flow', cf.operating?.net_operating_cash_flow, 0, true);

  b.nl(8);
  b.heading('Investing Activities', { size: 9 });
  b.financialRow('Token Treasury Movement', cf.investing?.token_treasury_movement, 1);
  b.financialRow('Net Investing Cash Flow', cf.investing?.net_investing_cash_flow, 0, true);

  b.nl(8);
  b.heading('Financing Activities', { size: 9 });
  b.financialRow('Funding Received', cf.financing?.funding_received, 1);
  b.financialRow('Net Financing Cash Flow', cf.financing?.net_financing_cash_flow, 0, true);

  b.nl(8);
  b.heading('Summary', { size: 9 });
  b.financialRow('Opening Cash Balance', cf.summary?.opening_cash_balance, 1);
  b.financialRow('Net Change in Cash', cf.summary?.net_cash_change, 1);
  b.financialRow('Closing Cash Balance', cf.summary?.closing_cash_balance, 0, true);
  b.nl(4);
  b.financialRow('Monthly Burn Rate', cf.summary?.monthly_burn_rate, 1);
  b.financialRow('Treasury Runway', cf.summary?.runway_months ? `${Math.floor(cf.summary.runway_months)} months` : 'N/A', 1);

  if (docs.cfo_commentary?.cf) {
    b.nl(10);
    b.heading('CFO Commentary', { size: 9 });
    b.hr('#e2e8f0', 0.5);
    b.body(docs.cfo_commentary.cf, { size: 8.5, gap: 6 });
  }
}

function renderBalanceSheet(b, docs) {
  b.newPage();
  b.heading('Balance Sheet', { size: 14 });
  b.caption(`As of end of ${docs.period} | Currency: USD`);
  b.hr();

  const bs = docs.balance_sheet;
  if (!bs) { b.body('No data available.'); return; }

  b.heading('Assets', { size: 9 });
  b.body('Current Assets', { bold: true, size: 8 });
  b.financialRow('Cash & Stablecoins', bs.assets?.current?.cash_and_stablecoins, 2);
  b.financialRow('Accounts Receivable', bs.assets?.current?.accounts_receivable, 2);
  b.financialRow('Total Current Assets', bs.assets?.current?.total_current_assets, 1, true);
  b.nl(4);
  b.body('Non-Current Assets', { bold: true, size: 8 });
  b.financialRow(`Token Treasury (${bs.meta?.token_price ? usd(bs.meta.token_price) + ' per token' : 'no token'})`, bs.assets?.non_current?.token_treasury_value, 2);
  b.financialRow('Total Non-Current Assets', bs.assets?.non_current?.total_non_current_assets, 1, true);
  b.financialRow('TOTAL ASSETS', bs.assets?.total_assets, 0, true);

  b.nl(8);
  b.heading('Liabilities', { size: 9 });
  b.financialRow('Accrued Expenses', bs.liabilities?.current?.accrued_expenses, 2);
  b.financialRow('Total Current Liabilities', bs.liabilities?.current?.total_current_liab, 1, true);
  b.financialRow('Vesting Obligations', bs.liabilities?.non_current?.vesting_obligations, 2);
  b.financialRow('Total Non-Current Liabilities', bs.liabilities?.non_current?.total_non_current_liab, 1, true);
  b.financialRow('TOTAL LIABILITIES', bs.liabilities?.total_liabilities, 0, true);

  b.nl(8);
  b.heading('Equity', { size: 9 });
  b.financialRow('Total Funding Raised', bs.equity?.total_funding_raised, 2);
  b.financialRow('Retained Earnings / (Deficit)', bs.equity?.retained_earnings, 2);
  b.financialRow('TOTAL EQUITY', bs.equity?.total_equity, 0, true);

  if (docs.cfo_commentary?.bs) {
    b.nl(10);
    b.heading('CFO Commentary', { size: 9 });
    b.hr('#e2e8f0', 0.5);
    b.body(docs.cfo_commentary.bs, { size: 8.5, gap: 6 });
  }
}

function renderUnitEconomics(b, docs) {
  b.newPage();
  b.heading('Unit Economics', { size: 14 });
  b.caption(`Period: ${docs.period}`);
  b.hr();

  const ue = docs.unit_economics;
  if (!ue) { b.body('No data available.'); return; }

  const rows = [
    ['New Users Acquired', (ue.acquisition?.new_users || 0).toLocaleString()],
    ['Marketing Spend', usd(ue.acquisition?.marketing_spend)],
    ['Customer Acquisition Cost (CAC)', ue.acquisition?.cac_label || 'N/A'],
    ['—', ''],
    ['Total Revenue', usd(ue.monetisation?.total_revenue)],
    ['Active Users', (ue.monetisation?.active_users || 0).toLocaleString()],
    ['Average Revenue Per User (ARPU)', usd(ue.monetisation?.arpu)],
    ['—', ''],
    ['Avg Retention (months)', String(ue.lifetime_value?.avg_retention_months || 'N/A')],
    ['Lifetime Value (LTV)', usd(ue.lifetime_value?.ltv)],
    ['—', ''],
    ['LTV:CAC Ratio', ue.ratios?.ltv_cac_label || 'N/A'],
    ['Payback Period', ue.ratios?.payback_label || 'N/A'],
    ['—', ''],
    ['Total Transactions', (ue.transactions?.total_transactions || 0).toLocaleString()],
    ['Revenue per Transaction', usd(ue.transactions?.revenue_per_tx)],
    ['Cost per Transaction', usd(ue.transactions?.cost_per_tx)],
    ['Profit per Transaction', usd(ue.transactions?.profit_per_tx)],
    ['—', ''],
    ['Monthly Burn Rate', usd(ue.burn_and_runway?.total_monthly_burn)],
    ['Cash Balance', usd(ue.burn_and_runway?.cash_balance)],
    ['Runway', ue.burn_and_runway?.runway_label || 'N/A'],
  ];

  b.tableHeader([{ text: 'Metric', width: bodyW * 0.6 }, { text: 'Value', width: bodyW * 0.4 }]);
  let alt = false;
  for (const [label, value] of rows) {
    if (label === '—') { b.nl(4); continue; }
    b.tableRow([
      { text: label, width: bodyW * 0.6 },
      { text: value, width: bodyW * 0.4, bold: true, align: 'right' },
    ], alt ? { bg: '#f7fafc' } : {});
    alt = !alt;
  }

  if (docs.cfo_commentary?.ue) {
    b.nl(10);
    b.heading('CFO Commentary', { size: 9 });
    b.hr('#e2e8f0', 0.5);
    b.body(docs.cfo_commentary.ue, { size: 8.5, gap: 6 });
  }
}

function renderForwardModel(b, docs) {
  b.newPage();
  b.heading('12-Month Forward Model', { size: 14 });
  b.caption('Base / Bull / Bear scenarios — for planning purposes only');
  b.hr();

  const fm = docs.forward_model;
  if (!fm) { b.body('No data available.'); return; }

  for (const scenario of [fm.base, fm.bull, fm.bear]) {
    b.checkPage(120);
    b.heading(scenario?.label || 'Scenario', { size: 10 });
    b.body(`Revenue growth: ${scenario?.assumptions?.monthly_revenue_growth || 'N/A'}/mo | Cost growth: ${scenario?.assumptions?.monthly_cost_growth || 'N/A'}/mo | Break-even: Month ${scenario?.break_even_month || 'N/A'}`, { size: 8 });
    b.nl(4);

    const colW = bodyW / 4;
    b.tableHeader([
      { text: 'Month', width: colW * 0.6 },
      { text: 'Revenue', width: colW * 1.1 },
      { text: 'Costs', width: colW * 1.1 },
      { text: 'Profit', width: colW * 1.2 },
    ]);

    let alt = false;
    for (const m of (scenario?.months || [])) {
      const isProfit = (m.projected_profit || 0) >= 0;
      b.tableRow([
        { text: `Month ${m.month}`, width: colW * 0.6 },
        { text: usd(m.projected_revenue), width: colW * 1.1, align: 'right' },
        { text: usd(m.projected_costs), width: colW * 1.1, align: 'right' },
        { text: usd(m.projected_profit), width: colW * 1.2, align: 'right', color: isProfit ? C.pos : C.neg, bold: true },
      ], alt ? { bg: '#f7fafc' } : {});
      alt = !alt;
    }
    b.nl(12);
  }

  if (docs.forward_model?.notes) {
    b.nl(4);
    b.heading('Assumptions & Disclaimer', { size: 9 });
    for (const note of docs.forward_model.notes) {
      b.body('• ' + note, { size: 7.5, gap: 3 });
    }
  }
}

function renderRedFlagsAndQA(b, docs) {
  b.newPage();
  b.heading('Red Flags & Opportunities', { size: 14 });
  b.hr();

  if (docs.red_flags?.length > 0) {
    b.heading('⚠ Red Flags', { size: 10, color: C.neg });
    b.nl(4);
    for (const flag of docs.red_flags) {
      b.body('• ' + flag, { size: 8.5, gap: 5 });
    }
  }

  b.nl(12);

  if (docs.opportunities?.length > 0) {
    b.heading('✓ Opportunities', { size: 10, color: C.pos });
    b.nl(4);
    for (const op of docs.opportunities) {
      b.body('• ' + op, { size: 8.5, gap: 5 });
    }
  }

  if (docs.investor_qa?.length > 0) {
    b.checkPage(120);
    b.newPage();
    b.heading('Investor Q&A Preparation', { size: 14 });
    b.caption('Likely questions from Series A/B investors — with suggested responses');
    b.hr();

    for (const qa of docs.investor_qa) {
      b.checkPage(60);
      b.heading('Q: ' + qa.question, { size: 9, color: C.accent });
      b.body(qa.answer, { size: 8.5, gap: 10 });
      b.hr('#e2e8f0', 0.3);
    }
  }
}

// ── Main export function ───────────────────────────────────────────────────

export async function generateFinancialPDF(docs, meta = {}) {
  const { projectName = 'Unknown Project', contractAddress = '', chain = 'ethereum' } = meta;
  const period = docs.period || 'N/A';

  const filename = `${contractAddress}_${chain}_${period}.pdf`.replace(/[^a-zA-Z0-9._-]/g, '_');
  const outputPath = join(OUTPUT_DIR, filename);
  ensureDir(outputPath);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 0, autoFirstPage: false });
    const stream = createWriteStream(outputPath);

    doc.pipe(stream);

    // We'll track page count manually
    let pageNum = 0;
    doc.on('pageAdded', () => { pageNum++; });

    const b = new PDFBuilder(doc);

    // Page 1 — Cover
    doc.addPage();
    renderCover(b, docs, projectName, period, chain);

    // Page 2 — Executive Summary
    renderExecutiveSummary(b, docs);

    // Page 3 — Income Statement
    renderIncomeStatement(b, docs);

    // Page 4 — Cash Flow
    renderCashFlow(b, docs);

    // Page 5 — Balance Sheet
    renderBalanceSheet(b, docs);

    // Page 6 — Unit Economics
    renderUnitEconomics(b, docs);

    // Page 7 — 12-Month Forward Model
    renderForwardModel(b, docs);

    // Page 8/9 — Red Flags + Investor Q&A
    renderRedFlagsAndQA(b, docs);

    // Finalize
    doc.end();

    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
  });
}
