/**
 * MongoDB schemas for enriched agent intelligence.
 * Stores per-user, per-contract intelligence that the file storage doesn't have:
 * - On-chain risk analysis (ownership, concentration, proxy)
 * - GitHub developer health
 * - Combined intelligence scores
 * - Agent research reports
 */

import mongoose from 'mongoose';

// ── Intelligence Analysis ─────────────────────────────────────────────────────
// One document per user+contract analysis run

const intelligenceSchema = new mongoose.Schema({
  userId:          { type: String, required: true, index: true },
  contractAddress: { type: String, required: true },
  chain:           { type: String, required: true },
  contractName:    { type: String },

  // Scores (0–100)
  tractionScore:        Number,
  riskScore:            Number,
  sustainabilityScore:  Number,
  communityHealthScore: Number,
  growthProbability:    Number,
  confidenceInterval:   Number,
  riskLevel:            { type: String, enum: ['low', 'medium', 'high', 'critical'] },

  // Risk signals array
  riskSignals: [String],

  // Raw collected data
  onChainDetails:  mongoose.Schema.Types.Mixed,  // ownership, concentration, proxy
  githubMetrics:   mongoose.Schema.Types.Mixed,  // commits, contributors, devHealthScore
  sentimentMetrics: mongoose.Schema.Types.Mixed, // twitter sentiment (future)

  // AI report
  aiReport:    String,   // plain-English report from Gemini
  components:  mongoose.Schema.Types.Mixed, // frontend render components

}, { timestamps: true });

intelligenceSchema.index({ userId: 1, contractAddress: 1, createdAt: -1 });

// ── Agent Research Report ─────────────────────────────────────────────────────
// Stores autonomous research reports generated by the agent

const researchReportSchema = new mongoose.Schema({
  userId:          { type: String, required: true, index: true },
  contractAddress: { type: String },
  chain:           { type: String },
  content:         { type: String, required: true },
  components:      mongoose.Schema.Types.Mixed,
  toolsUsed:       [String],
  source:          { type: String, default: 'manual' }, // manual | proactive | scheduled
}, { timestamps: true });

researchReportSchema.index({ userId: 1, createdAt: -1 });

// ── Models ────────────────────────────────────────────────────────────────────

export const IntelligenceModel  = mongoose.models.Intelligence  || mongoose.model('Intelligence',  intelligenceSchema);
export const ResearchReportModel = mongoose.models.ResearchReport || mongoose.model('ResearchReport', researchReportSchema);

// ── Storage API ───────────────────────────────────────────────────────────────

export const IntelligenceStorage = {
  async save(userId, contractAddress, chain, data) {
    return IntelligenceModel.create({ userId, contractAddress, chain, ...data });
  },

  async getLatest(userId, contractAddress) {
    return IntelligenceModel
      .findOne({ userId, contractAddress })
      .sort({ createdAt: -1 });
  },

  async getHistory(userId, limit = 10) {
    return IntelligenceModel
      .find({ userId })
      .sort({ createdAt: -1 })
      .limit(limit)
      .select('contractAddress chain riskScore tractionScore riskLevel createdAt');
  },
};

export const ResearchReportStorage = {
  async save(userId, data) {
    return ResearchReportModel.create({ userId, ...data });
  },

  async getLatest(userId) {
    return ResearchReportModel.findOne({ userId }).sort({ createdAt: -1 });
  },

  async getHistory(userId, limit = 20) {
    return ResearchReportModel
      .find({ userId })
      .sort({ createdAt: -1 })
      .limit(limit)
      .select('contractAddress chain content source createdAt');
  },
};
